; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @llvm.assume(i1 noundef)
declare void @func1()
declare void @func2()

define i32 @udiv_variable(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @udiv_variable(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[DIV:.*]], label %[[EXIT:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    br label %[[DIV1:.*]]
; CHECK:       [[DIV1]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv exact i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = urem i32 %x, %y
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %middle, label %exit

middle:
  br label %div

div:
  %quot = udiv i32 %x, %y
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @udiv_constant(i32 %x) {
; CHECK-LABEL: define i32 @udiv_constant(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], 7
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[DIV:.*]], label %[[EXIT:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv exact i32 [[X]], 7
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = urem i32 %x, 7
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %div, label %exit

div:
  %quot = udiv i32 %x, 7
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @sdiv_variable(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @sdiv_variable(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = srem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[DIV:.*]], label %[[EXIT:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = sdiv exact i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = srem i32 %x, %y
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %div, label %exit

div:
  %quot = sdiv i32 %x, %y
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @udiv_inverted_unreachable(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @udiv_inverted_unreachable(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[NOT_ZERO_NOT:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[NOT_ZERO_NOT]], label %[[DIV:.*]], label %[[UNREACHABLE:.*]]
; CHECK:       [[UNREACHABLE]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv exact i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
;
entry:
  %rem = urem i32 %x, %y
  %not.zero = icmp ne i32 %rem, 0
  br i1 %not.zero, label %unreachable, label %div

unreachable:
  unreachable

div:
  %quot = udiv i32 %x, %y
  ret i32 %quot
}

define i32 @udiv_assume(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @udiv_assume(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_ZERO]])
; CHECK-NEXT:    [[QUOT:%.*]] = udiv exact i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
;
  %rem = urem i32 %x, %y
  %is.zero = icmp eq i32 %rem, 0
  call void @llvm.assume(i1 %is.zero)
  %quot = udiv i32 %x, %y
  ret i32 %quot
}

define i32 @udiv_condition_on_other_path(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @udiv_condition_on_other_path(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[ZERO:.*]], label %[[NONZERO:.*]]
; CHECK:       [[ZERO]]:
; CHECK-NEXT:    call void @func1()
; CHECK-NEXT:    [[ZERO_QUOT:%.*]] = udiv exact i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[ZERO_QUOT]]
; CHECK:       [[NONZERO]]:
; CHECK-NEXT:    call void @func2()
; CHECK-NEXT:    [[QUOT:%.*]] = udiv i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
;
entry:
  %rem = urem i32 %x, %y
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %zero, label %nonzero

zero:
  call void @func1()
  %zero.quot = udiv i32 %x, %y
  ret i32 %zero.quot

nonzero:
  call void @func2()
  %nonzero.quot = udiv i32 %x, %y
  ret i32 %nonzero.quot
}

define i32 @udiv_different_divisor(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @udiv_different_divisor(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Z]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[DIV:.*]], label %[[EXIT:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = urem i32 %x, %z
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %div, label %exit

div:
  %quot = udiv i32 %x, %y
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @udiv_different_dividend(i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: define i32 @udiv_different_dividend(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]], i32 [[Z:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[Z]], [[Y]]
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[IS_ZERO]], label %[[DIV:.*]], label %[[EXIT:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = urem i32 %z, %y
  %is.zero = icmp eq i32 %rem, 0
  br i1 %is.zero, label %div, label %exit

div:
  %quot = udiv i32 %x, %y
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @udiv_known_nonzero_remainder(i32 %x, i32 %y) {
; CHECK-LABEL: define i32 @udiv_known_nonzero_remainder(
; CHECK-SAME: i32 [[X:%.*]], i32 [[Y:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], [[Y]]
; CHECK-NEXT:    [[NOT_ZERO_NOT:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[NOT_ZERO_NOT]], label %[[EXIT:.*]], label %[[DIV:.*]]
; CHECK:       [[DIV]]:
; CHECK-NEXT:    [[QUOT:%.*]] = udiv i32 [[X]], [[Y]]
; CHECK-NEXT:    ret i32 [[QUOT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i32 0
;
entry:
  %rem = urem i32 %x, %y
  %not.zero = icmp ne i32 %rem, 0
  br i1 %not.zero, label %div, label %exit

div:
  %quot = udiv i32 %x, %y
  ret i32 %quot

exit:
  ret i32 0
}

define i32 @div_exact_3(i32 %x) {
; CHECK-LABEL: define i32 @div_exact_3(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:    [[REM:%.*]] = urem i32 [[X]], 3
; CHECK-NEXT:    [[IS_ZERO:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[IS_ZERO]])
; CHECK-NEXT:    [[QUOT:%.*]] = udiv exact i32 [[X]], 3
; CHECK-NEXT:    ret i32 [[QUOT]]
;
  %rem = urem i32 %x, 3
  %is.zero = icmp eq i32 %rem, 0
  call void @llvm.assume(i1 %is.zero)
  %quot = udiv i32 %x, 3
  ret i32 %quot
}
