; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

; These test the "convert to float to count leading zeros" idiom (as used,
; e.g., with cvtdq2ps on SSE2/AVX2), where the bit pattern of a uitofp/sitofp
; result is inspected directly via a bitcast to recover an exponent that
; encodes the position of the highest set bit.

define i1 @test_uitofp_sign_scalar(i32 %x) {
; CHECK-LABEL: @test_uitofp_sign_scalar(
; CHECK-NEXT:    ret i1 false
;
  %f = uitofp i32 %x to float
  %bc = bitcast float %f to i32
  %sign = icmp slt i32 %bc, 0
  ret i1 %sign
}

; SSE2-width (128-bit, 4 x i32) vector uitofp: the result is always
; non-negative, regardless of %x, since unsigned values never convert to a
; negative float.
define <4 x i1> @test_uitofp_sign_v4i32(<4 x i32> %x) {
; CHECK-LABEL: @test_uitofp_sign_v4i32(
; CHECK-NEXT:    ret <4 x i1> zeroinitializer
;
  %f = uitofp <4 x i32> %x to <4 x float>
  %bc = bitcast <4 x float> %f to <4 x i32>
  %sign = icmp slt <4 x i32> %bc, zeroinitializer
  ret <4 x i1> %sign
}

; AVX2-width (256-bit, 8 x i32) version of the same fact.
define <8 x i1> @test_uitofp_sign_v8i32(<8 x i32> %x) {
; CHECK-LABEL: @test_uitofp_sign_v8i32(
; CHECK-NEXT:    ret <8 x i1> zeroinitializer
;
  %f = uitofp <8 x i32> %x to <8 x float>
  %bc = bitcast <8 x float> %f to <8 x i32>
  %sign = icmp slt <8 x i32> %bc, zeroinitializer
  ret <8 x i1> %sign
}

; Forcing the top bit of an i8 (via `or ... 128`) pins the magnitude to
; [128, 255], which always converts exactly (no rounding) to a float with
; biased exponent 134 -- so the whole exponent field of the converted bit
; pattern is known, not just the class of the value.
define i1 @test_uitofp_exponent_exact_scalar(i8 %x8) {
; CHECK-LABEL: @test_uitofp_exponent_exact_scalar(
; CHECK-NEXT:    ret i1 true
;
  %m = or i8 %x8, 128
  %x = zext i8 %m to i32
  %f = uitofp i32 %x to float
  %bc = bitcast float %f to i32
  %exp = and i32 %bc, 2130706432
  %cmp = icmp eq i32 %exp, 1124073472
  ret i1 %cmp
}

define <4 x i1> @test_uitofp_exponent_exact_v4i32(<4 x i8> %x8) {
; CHECK-LABEL: @test_uitofp_exponent_exact_v4i32(
; CHECK-NEXT:    ret <4 x i1> splat (i1 true)
;
  %m = or <4 x i8> %x8, splat (i8 128)
  %x = zext <4 x i8> %m to <4 x i32>
  %f = uitofp <4 x i32> %x to <4 x float>
  %bc = bitcast <4 x float> %f to <4 x i32>
  %exp = and <4 x i32> %bc, splat (i32 2130706432)
  %cmp = icmp eq <4 x i32> %exp, splat (i32 1124073472)
  ret <4 x i1> %cmp
}

define <8 x i1> @test_uitofp_exponent_exact_v8i32(<8 x i8> %x8) {
; CHECK-LABEL: @test_uitofp_exponent_exact_v8i32(
; CHECK-NEXT:    ret <8 x i1> splat (i1 true)
;
  %m = or <8 x i8> %x8, splat (i8 128)
  %x = zext <8 x i8> %m to <8 x i32>
  %f = uitofp <8 x i32> %x to <8 x float>
  %bc = bitcast <8 x float> %f to <8 x i32>
  %exp = and <8 x i32> %bc, splat (i32 2130706432)
  %cmp = icmp eq <8 x i32> %exp, splat (i32 1124073472)
  ret <8 x i1> %cmp
}

; sitofp of a value known to be in [-256, -1] (forced negative, magnitude
; bounded) is always negative.
define i1 @test_sitofp_sign_and_bound(i32 %x) {
; CHECK-LABEL: @test_sitofp_sign_and_bound(
; CHECK-NEXT:    ret i1 true
;
  %m = and i32 %x, 255
  %neg = or i32 %m, -256
  %f = sitofp i32 %neg to float
  %bc = bitcast float %f to i32
  %sign = icmp slt i32 %bc, 0
  ret i1 %sign
}
