; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

declare bfloat @llvm.log.bf16(bfloat)
declare half @llvm.log.f16(half)
declare float @llvm.log.f32(float)
declare double @llvm.log.f64(double)
declare fp128 @llvm.log.f128(fp128)
declare x86_fp80 @llvm.log.f80(x86_fp80)
declare ppc_fp128 @llvm.log.ppcf128(ppc_fp128)

declare i1 @llvm.is.fpclass.bf16(bfloat, i32 immarg)
declare i1 @llvm.is.fpclass.f16(half, i32 immarg)
declare i1 @llvm.is.fpclass.f32(float, i32 immarg)
declare i1 @llvm.is.fpclass.f64(double, i32 immarg)
declare i1 @llvm.is.fpclass.f128(fp128, i32 immarg)
declare i1 @llvm.is.fpclass.f80(x86_fp80, i32 immarg)
declare i1 @llvm.is.fpclass.ppcf128(ppc_fp128, i32 immarg)

define i1 @log_bf16_is_nzero_or_subnormal(bfloat %arg) {
; CHECK-LABEL: define i1 @log_bf16_is_nzero_or_subnormal(
; CHECK-SAME: bfloat [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call bfloat @llvm.log.bf16(bfloat %arg)
  %class = call i1 @llvm.is.fpclass.bf16(bfloat %log, i32 176)
  ret i1 %class
}

define i1 @log_f16_is_nzero_or_subnormal(half %arg) {
; CHECK-LABEL: define i1 @log_f16_is_nzero_or_subnormal(
; CHECK-SAME: half [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call half @llvm.log.f16(half %arg)
  %class = call i1 @llvm.is.fpclass.f16(half %log, i32 176)
  ret i1 %class
}

define i1 @log_f32_is_nzero_or_subnormal(float %arg) {
; CHECK-LABEL: define i1 @log_f32_is_nzero_or_subnormal(
; CHECK-SAME: float [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call float @llvm.log.f32(float %arg)
  %class = call i1 @llvm.is.fpclass.f32(float %log, i32 176)
  ret i1 %class
}

define i1 @log_f64_is_nzero_or_subnormal(double %arg) {
; CHECK-LABEL: define i1 @log_f64_is_nzero_or_subnormal(
; CHECK-SAME: double [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call double @llvm.log.f64(double %arg)
  %class = call i1 @llvm.is.fpclass.f64(double %log, i32 176)
  ret i1 %class
}

define i1 @log_f128_is_nzero_or_subnormal(fp128 %arg) {
; CHECK-LABEL: define i1 @log_f128_is_nzero_or_subnormal(
; CHECK-SAME: fp128 [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call fp128 @llvm.log.f128(fp128 %arg)
  %class = call i1 @llvm.is.fpclass.f128(fp128 %log, i32 176)
  ret i1 %class
}

define i1 @log_f80_is_nzero_or_subnormal(x86_fp80 %arg) {
; CHECK-LABEL: define i1 @log_f80_is_nzero_or_subnormal(
; CHECK-SAME: x86_fp80 [[ARG:%.*]]) {
; CHECK-NEXT:    ret i1 false
;
  %log = call x86_fp80 @llvm.log.f80(x86_fp80 %arg)
  %class = call i1 @llvm.is.fpclass.f80(x86_fp80 %log, i32 176)
  ret i1 %class
}

define i1 @log_ppcf128_is_subnormal(ppc_fp128 %arg) {
; CHECK-LABEL: define i1 @log_ppcf128_is_subnormal(
; CHECK-SAME: ppc_fp128 [[ARG:%.*]]) {
; CHECK-NEXT:    [[LOG:%.*]] = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 [[ARG]])
; CHECK-NEXT:    [[CLASS:%.*]] = call i1 @llvm.is.fpclass.ppcf128(ppc_fp128 [[LOG]], /* (sub) */ i32 144)
; CHECK-NEXT:    ret i1 [[CLASS]]
;
  %log = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 %arg)
  %class = call i1 @llvm.is.fpclass.ppcf128(ppc_fp128 %log, i32 144)
  ret i1 %class
}

define i1 @log_ppcf128_is_nzero(ppc_fp128 %arg) {
; CHECK-LABEL: define i1 @log_ppcf128_is_nzero(
; CHECK-SAME: ppc_fp128 [[ARG:%.*]]) {
; CHECK-NEXT:    [[LOG:%.*]] = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 [[ARG]])
; CHECK-NEXT:    [[CLASS:%.*]] = call i1 @llvm.is.fpclass.ppcf128(ppc_fp128 [[LOG]], /* (nzero) */ i32 32)
; CHECK-NEXT:    ret i1 [[CLASS]]
;
  %log = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 %arg)
  %class = call i1 @llvm.is.fpclass.ppcf128(ppc_fp128 %log, i32 32)
  ret i1 %class
}
