; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6

; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s

declare float @llvm.sqrt.f32(float)

; The only negative value sqrt(x) can produce is -0.0, so the only negative
; value 1.0 / sqrt(x) can produce is -Inf.
; TODO: Also infer that the result cannot be -0.0.
define float @ret_inv_sqrt(float %x) {
; CHECK-LABEL: define nofpclass(nsub nnorm) float @ret_inv_sqrt(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float [[X]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    [[INV_SQRT:%.*]] = fdiv float 1.000000e+00, [[SQRT]]
; CHECK-NEXT:    ret float [[INV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %inv.sqrt = fdiv float 1.0, %sqrt
  ret float %inv.sqrt
}

; Positive infinity and positive zero are impossible here. However, they are
; reported as being possible because fdiv is not aware that the LHS is one.
; fdiv only knows that it is computing the result of (normal / normal), which
; may overflow to infinity or underflow to zero.
; TODO: Also infer that the result cannot be +0.0 or +Inf.
define float @ret_inv_sqrt_x_not_infinity_not_zero(float nofpclass(inf zero) %x) {
; CHECK-LABEL: define nofpclass(ninf nzero nsub nnorm) float @ret_inv_sqrt_x_not_infinity_not_zero(
; CHECK-SAME: float nofpclass(inf zero) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(inf zero) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[INV_SQRT:%.*]] = fdiv float 1.000000e+00, [[SQRT]]
; CHECK-NEXT:    ret float [[INV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float nofpclass(inf zero) %x)
  %inv.sqrt = fdiv float 1.0, %sqrt
  ret float %inv.sqrt
}

define float @ret_inv_sqrt_x_nonzero_finite_positive(float nofpclass(nan inf zero nsub nnorm) %x) {
; CHECK-LABEL: define nofpclass(nan ninf nzero nsub nnorm) float @ret_inv_sqrt_x_nonzero_finite_positive(
; CHECK-SAME: float nofpclass(nan inf zero nsub nnorm) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub nnorm) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[INV_SQRT:%.*]] = fdiv float 1.000000e+00, [[SQRT]]
; CHECK-NEXT:    ret float [[INV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub nnorm) %x)
  %inv.sqrt = fdiv float 1.0, %sqrt
  ret float %inv.sqrt
}

; sqrt(1.0 / x) may produce -0.0 when x is -Inf, but cannot produce any other
; negative value or a subnormal value.
define float @ret_sqrt_inv(float %x) {
; CHECK-LABEL: define nofpclass(ninf sub nnorm) float @ret_sqrt_inv(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[INV:%.*]] = fdiv float 1.000000e+00, [[X]]
; CHECK-NEXT:    [[SQRT_INV:%.*]] = call nofpclass(ninf sub nnorm) float @llvm.sqrt.f32(float [[INV]]) #[[ATTR2]]
; CHECK-NEXT:    ret float [[SQRT_INV]]
;
  %inv = fdiv float 1.0, %x
  %sqrt.inv = call float @llvm.sqrt.f32(float %inv)
  ret float %sqrt.inv
}

define float @ret_sqrt_inv_not_infinity_not_zero(float nofpclass(inf zero) %x) {
; CHECK-LABEL: define nofpclass(ninf sub nnorm) float @ret_sqrt_inv_not_infinity_not_zero(
; CHECK-SAME: float nofpclass(inf zero) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[INV:%.*]] = fdiv float 1.000000e+00, [[X]]
; CHECK-NEXT:    [[SQRT_INV:%.*]] = call nofpclass(ninf sub nnorm) float @llvm.sqrt.f32(float [[INV]]) #[[ATTR2]]
; CHECK-NEXT:    ret float [[SQRT_INV]]
;
  %inv = fdiv float 1.0, %x
  %sqrt.inv = call float @llvm.sqrt.f32(float %inv)
  ret float %sqrt.inv
}

define float @ret_sqrt_inv_nonzero_finite_positive(float nofpclass(nan inf zero nsub nnorm) %x) {
; CHECK-LABEL: define nofpclass(nan ninf nzero sub nnorm) float @ret_sqrt_inv_nonzero_finite_positive(
; CHECK-SAME: float nofpclass(nan inf zero nsub nnorm) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[INV:%.*]] = fdiv float 1.000000e+00, [[X]]
; CHECK-NEXT:    [[SQRT_INV:%.*]] = call nofpclass(nan ninf nzero sub nnorm) float @llvm.sqrt.f32(float [[INV]]) #[[ATTR2]]
; CHECK-NEXT:    ret float [[SQRT_INV]]
;
  %inv = fdiv float 1.0, %x
  %sqrt.inv = call float @llvm.sqrt.f32(float %inv)
  ret float %sqrt.inv
}

; TODO: sqrt(x) / x can only produce a positive normal value or NaN.
define float @ret_sqrt_x_div_x(float %x) {
; CHECK-LABEL: define float @ret_sqrt_x_div_x(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[SQRT_DIV:%.*]] = fdiv float [[SQRT]], [[X]]
; CHECK-NEXT:    ret float [[SQRT_DIV]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %sqrt.div = fdiv float %sqrt, %x
  ret float %sqrt.div
}

define float @ret_sqrt_x_div_x_not_infinity_not_zero(float nofpclass(inf zero) %x) {
; CHECK-LABEL: define float @ret_sqrt_x_div_x_not_infinity_not_zero(
; CHECK-SAME: float nofpclass(inf zero) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(inf zero) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[SQRT_DIV:%.*]] = fdiv float [[SQRT]], [[X]]
; CHECK-NEXT:    ret float [[SQRT_DIV]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %sqrt.div = fdiv float %sqrt, %x
  ret float %sqrt.div
}

define float @ret_sqrt_x_div_x_nonzero_finite_positive(float nofpclass(nan inf zero nsub nnorm) %x) {
; CHECK-LABEL: define nofpclass(nan ninf nzero nsub nnorm) float @ret_sqrt_x_div_x_nonzero_finite_positive(
; CHECK-SAME: float nofpclass(nan inf zero nsub nnorm) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub nnorm) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[SQRT_DIV:%.*]] = fdiv float [[SQRT]], [[X]]
; CHECK-NEXT:    ret float [[SQRT_DIV]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %sqrt.div = fdiv float %sqrt, %x
  ret float %sqrt.div
}

; TODO: x / sqrt(x) can only produce a positive normal value or NaN.
define float @ret_x_div_sqrt_x(float %x) {
; CHECK-LABEL: define float @ret_x_div_sqrt_x(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[X_DIV_SQRT:%.*]] = fdiv float [[X]], [[SQRT]]
; CHECK-NEXT:    ret float [[X_DIV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %x.div.sqrt = fdiv float %x, %sqrt
  ret float %x.div.sqrt
}

define float @ret_x_div_sqrt_x_not_infinity_not_zero(float nofpclass(inf zero) %x) {
; CHECK-LABEL: define float @ret_x_div_sqrt_x_not_infinity_not_zero(
; CHECK-SAME: float nofpclass(inf zero) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(inf zero) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[X_DIV_SQRT:%.*]] = fdiv float [[X]], [[SQRT]]
; CHECK-NEXT:    ret float [[X_DIV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %x.div.sqrt = fdiv float %x, %sqrt
  ret float %x.div.sqrt
}

define float @ret_x_div_sqrt_x_nonzero_finite_positive(float nofpclass(nan inf zero nsub nnorm) %x) {
; CHECK-LABEL: define nofpclass(nan ninf nzero nsub nnorm) float @ret_x_div_sqrt_x_nonzero_finite_positive(
; CHECK-SAME: float nofpclass(nan inf zero nsub nnorm) [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub nnorm) [[X]]) #[[ATTR2]]
; CHECK-NEXT:    [[X_DIV_SQRT:%.*]] = fdiv float [[X]], [[SQRT]]
; CHECK-NEXT:    ret float [[X_DIV_SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %x)
  %x.div.sqrt = fdiv float %x, %sqrt
  ret float %x.div.sqrt
}

; The only negative value sqrt(-x) can produce is -0.0, so the only positive
; value -1.0 / sqrt(-x) can produce is +Inf.
; TODO: Also infer that the result cannot be +0.0.
define float @ret_neg_inv_sqrt_neg(float %x) {
; CHECK-LABEL: define nofpclass(psub pnorm) float @ret_neg_inv_sqrt_neg(
; CHECK-SAME: float [[X:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[NEG_X:%.*]] = fneg float [[X]]
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float [[NEG_X]]) #[[ATTR2]]
; CHECK-NEXT:    [[NEG_INV_SQRT:%.*]] = fdiv float -1.000000e+00, [[SQRT]]
; CHECK-NEXT:    ret float [[NEG_INV_SQRT]]
;
  %neg.x = fneg float %x
  %sqrt = call float @llvm.sqrt.f32(float %neg.x)
  %neg.inv.sqrt = fdiv float -1.0, %sqrt
  ret float %neg.inv.sqrt
}
