; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s
target triple = "x86_64-unknown-linux-gnu"

; Without a memory(none)/readnone attribute, the call could write errno, so
; getIntrinsicForCallSite (and therefore computeKnownFPClass) must not treat
; these as the corresponding libm intrinsics.

declare double @log(double)
declare double @sqrt(double)
declare double @exp(double)

define double @ret_log(double %arg) {
; CHECK-LABEL: @ret_log(
; CHECK-NEXT:    [[CALL:%.*]] = call double @log(double [[ARG:%.*]])
; CHECK-NEXT:    ret double [[CALL]]
;
  %call = call double @log(double %arg)
  ret double %call
}

define double @ret_sqrt(double %arg) {
; CHECK-LABEL: @ret_sqrt(
; CHECK-NEXT:    [[CALL:%.*]] = call double @sqrt(double [[ARG:%.*]])
; CHECK-NEXT:    ret double [[CALL]]
;
  %call = call double @sqrt(double %arg)
  ret double %call
}

define double @ret_exp(double %arg) {
; CHECK-LABEL: @ret_exp(
; CHECK-NEXT:    [[CALL:%.*]] = call double @exp(double [[ARG:%.*]])
; CHECK-NEXT:    ret double [[CALL]]
;
  %call = call double @exp(double %arg)
  ret double %call
}
