; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s
target triple = "x86_64-unknown-linux-gnu"

declare float @sqrtf(float) memory(none)
declare double @sqrt(double) memory(none)
declare float @logf(float) memory(none)
declare double @log(double) memory(none)
declare float @expf(float) memory(none)
declare double @exp(double) memory(none)

define float @ret_sqrtf(float %arg) {
; CHECK-LABEL: @ret_sqrtf(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(ninf sub nnorm) float @sqrtf(float [[ARG:%.*]]) #[[ATTR3:[0-9]+]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @sqrtf(float %arg)
  ret float %call
}

define double @ret_sqrt(double %arg) {
; CHECK-LABEL: @ret_sqrt(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(ninf sub nnorm) double @sqrt(double [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret double [[CALL]]
;
  %call = call double @sqrt(double %arg)
  ret double %call
}

define float @ret_logf(float %arg) {
; CHECK-LABEL: @ret_logf(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nzero sub) float @logf(float [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @logf(float %arg)
  ret float %call
}

define float @ret_log(float %arg) {
; CHECK-LABEL: @ret_log(
; CHECK-NEXT:    [[CALL:%.*]] = call float @log(float [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @log(float %arg)
  ret float %call
}

define float @ret_expf(float %arg) {
; CHECK-LABEL: @ret_expf(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(ninf nzero nsub nnorm) float @expf(float [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @expf(float %arg)
  ret float %call
}

define double @ret_exp(double %arg) {
; CHECK-LABEL: @ret_exp(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(ninf nzero nsub nnorm) double @exp(double [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret double [[CALL]]
;
  %call = call double @exp(double %arg)
  ret double %call
}

define float @ret_sqrtf_psub_pnorm_nonan(float nofpclass(nan inf zero nsub nnorm) %arg) {
; CHECK-LABEL: @ret_sqrtf_psub_pnorm_nonan(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf nzero sub nnorm) float @sqrtf(float nofpclass(nan inf zero nsub nnorm) [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @sqrtf(float %arg)
  ret float %call
}

define float @ret_sqrtf_psub_pnorm_mode_denormal_dynamic(float nofpclass(nan inf zero nsub nnorm) %arg) denormal_fpenv(dynamic|dynamic) {
; CHECK-LABEL: @ret_sqrtf_psub_pnorm_mode_denormal_dynamic(
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf nzero sub nnorm) float @sqrtf(float nofpclass(nan inf zero nsub nnorm) [[ARG:%.*]]) #[[ATTR3]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @sqrtf(float %arg)
  ret float %call
}
