; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s

declare bfloat @llvm.log.bf16(bfloat)
declare half @llvm.log.f16(half)
declare float @llvm.log.f32(float)
declare double @llvm.log.f64(double)
declare fp128 @llvm.log.f128(fp128)
declare x86_fp80 @llvm.log.f80(x86_fp80)
declare ppc_fp128 @llvm.log.ppcf128(ppc_fp128)

define bfloat @ret_log_bf16(bfloat %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) bfloat @ret_log_bf16(
; CHECK-SAME: bfloat [[ARG:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) bfloat @llvm.log.bf16(bfloat [[ARG]]) #[[ATTR2:[0-9]+]]
; CHECK-NEXT:    ret bfloat [[LOG]]
;
  %log = call bfloat @llvm.log.bf16(bfloat %arg)
  ret bfloat %log
}

define half @ret_log_f16(half %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) half @ret_log_f16(
; CHECK-SAME: half [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) half @llvm.log.f16(half [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret half [[LOG]]
;
  %log = call half @llvm.log.f16(half %arg)
  ret half %log
}

define float @ret_log_f32(float %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) float @ret_log_f32(
; CHECK-SAME: float [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) float @llvm.log.f32(float [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret float [[LOG]]
;
  %log = call float @llvm.log.f32(float %arg)
  ret float %log
}

define double @ret_log_f64(double %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) double @ret_log_f64(
; CHECK-SAME: double [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) double @llvm.log.f64(double [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret double [[LOG]]
;
  %log = call double @llvm.log.f64(double %arg)
  ret double %log
}

define fp128 @ret_log_f128(fp128 %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) fp128 @ret_log_f128(
; CHECK-SAME: fp128 [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) fp128 @llvm.log.f128(fp128 [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret fp128 [[LOG]]
;
  %log = call fp128 @llvm.log.f128(fp128 %arg)
  ret fp128 %log
}

define x86_fp80 @ret_log_f80(x86_fp80 %arg) {
; CHECK-LABEL: define nofpclass(nzero sub) x86_fp80 @ret_log_f80(
; CHECK-SAME: x86_fp80 [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call nofpclass(nzero sub) x86_fp80 @llvm.log.f80(x86_fp80 [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret x86_fp80 [[LOG]]
;
  %log = call x86_fp80 @llvm.log.f80(x86_fp80 %arg)
  ret x86_fp80 %log
}

define ppc_fp128 @ret_log_ppcf128(ppc_fp128 %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_log_ppcf128(
; CHECK-SAME: ppc_fp128 [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[LOG:%.*]] = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 [[ARG]]) #[[ATTR2]]
; CHECK-NEXT:    ret ppc_fp128 [[LOG]]
;
  %log = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 %arg)
  ret ppc_fp128 %log
}
