; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal < %s | FileCheck %s

declare ppc_fp128 @llvm.log.ppcf128(ppc_fp128)
declare ppc_fp128 @llvm.log10.ppcf128(ppc_fp128)
declare ppc_fp128 @llvm.log2.ppcf128(ppc_fp128)
declare ppc_fp128 @logl(ppc_fp128) memory(none)
declare ppc_fp128 @log2l(ppc_fp128) memory(none)
declare ppc_fp128 @log10l(ppc_fp128) memory(none)
declare ppc_fp128 @sinpil(ppc_fp128) memory(none)
declare ppc_fp128 @cospil(ppc_fp128) memory(none)
declare ppc_fp128 @tanpil(ppc_fp128) memory(none)
declare ppc_fp128 @lgammal(ppc_fp128) memory(none)
declare ppc_fp128 @compoundnl(ppc_fp128, i64) memory(none)

; We cannot rule out negative zero or subnormal here. ppc_fp128 can represent the
; exact value of 1.0 +/- subnormal, and log(1.0 +/- subnormal) may be zero or
; subnormal.
define ppc_fp128 @ret_log_ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define nofpclass(nan inf nzero sub) ppc_fp128 @ret_log_ppcf128(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf nzero sub) ppc_fp128 @llvm.log.ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR4:[0-9]+]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @llvm.log.ppcf128(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; |log2(x)| > |log(x)|. log2(1.0 + x) can be approximated by x * log2(e) or
; x * 1.442695 when x is close to zero, so it may technically be safe to rule
; out negative zero. This test watches for such a change.
define ppc_fp128 @ret_log2_ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define nofpclass(nan inf nzero sub) ppc_fp128 @ret_log2_ppcf128(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf nzero sub) ppc_fp128 @llvm.log2.ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR4]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @llvm.log2.ppcf128(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; |log10(x)| < |log(x)|
define ppc_fp128 @ret_log10_ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define nofpclass(nan inf nzero sub) ppc_fp128 @ret_log10_ppcf128(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf nzero sub) ppc_fp128 @llvm.log10.ppcf128(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR4]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @llvm.log10.ppcf128(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

define ppc_fp128 @ret_logl(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_logl(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @logl(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @logl(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

define ppc_fp128 @ret_log2l(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_log2l(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @log2l(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @log2l(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

define ppc_fp128 @ret_log10l(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_log10l(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @log10l(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @log10l(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; sinpi(1.0 + x) can be approximated by -pi * x or -3.14159 * x. Since
; -3.14159 * subnormal may still be subnormal, we cannot rule out subnormal.
define ppc_fp128 @ret_sinpil(ppc_fp128 nofpclass(nan inf zero sub) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_sinpil(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @sinpil(ppc_fp128 nofpclass(nan inf zero sub) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @sinpil(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; cospi(0.5 + x) can be approximated by -pi * x or -3.14159 * x. Since
; -3.14159 * subnormal may still be subnormal, we cannot rule out subnormal.
define ppc_fp128 @ret_cospil(ppc_fp128 nofpclass(nan inf zero sub) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_cospil(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @cospil(ppc_fp128 nofpclass(nan inf zero sub) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @cospil(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; tanpi(1.0 + x) can be approximated by pi * x or 3.14159 * x. Since
; 3.14159 * subnormal may still be subnormal, we cannot rule out subnormal.
define ppc_fp128 @ret_tanpil(ppc_fp128 nofpclass(nan inf zero sub) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_tanpil(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @tanpil(ppc_fp128 nofpclass(nan inf zero sub) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @tanpil(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; When x is close to zero:
; lgamma(1.0 + x) is approximated by -gamma * x or -0.577216 * x.
; lgamma(2.0 + x) is approximated by (1.0 - gamma) * x or 0.422784 * x.
; Therefore, lgamma(1.0 +/- subnormal) and lgamma(2.0 +/- subnormal) can
; generate subnormal or negative zero results. Technically, negative zero can
; be ruled out for some inputs depending on the rounding and denormal mode.
define ppc_fp128 @ret_lgammal(ppc_fp128 nofpclass(nan inf zero sub nnorm) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_lgammal(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @lgammal(ppc_fp128 nofpclass(nan inf zero sub nnorm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @lgammal(ppc_fp128 %arg)
  ret ppc_fp128 %call
}

; compoundn(-1.0 + subnormal, 1) = pown(subnormal, 1) = subnormal.
define ppc_fp128 @ret_compoundnl(ppc_fp128 nofpclass(nan inf zero sub pnorm) %arg) {
; CHECK-LABEL: define ppc_fp128 @ret_compoundnl(
; CHECK-SAME: ppc_fp128 nofpclass(nan inf zero sub pnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call ppc_fp128 @compoundnl(ppc_fp128 nofpclass(nan inf zero sub pnorm) [[ARG]], i64 noundef 1) #[[ATTR5]]
; CHECK-NEXT:    ret ppc_fp128 [[CALL]]
;
  %call = call ppc_fp128 @compoundnl(ppc_fp128 %arg, i64 1)
  ret ppc_fp128 %call
}
