; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s

declare float @llvm.atan.f32(float)

; atan is bounded to (-pi/2, pi/2), never Inf. atan(+-Inf) = +-pi/2 (finite).
define float @ret_atan(float %arg) {
; CHECK-LABEL: define nofpclass(inf) float @ret_atan(
; CHECK-SAME: float [[ARG:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float [[ARG]]) #[[ATTR11:[0-9]+]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_nan(float nofpclass(nan) %arg) {
; CHECK-LABEL: define nofpclass(nan inf) float @ret_atan_no_nan(
; CHECK-SAME: float nofpclass(nan) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(nan inf) float @llvm.atan.f32(float nofpclass(nan) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_snan(float nofpclass(snan) %arg) {
; CHECK-LABEL: define nofpclass(snan inf) float @ret_atan_no_snan(
; CHECK-SAME: float nofpclass(snan) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(snan inf) float @llvm.atan.f32(float nofpclass(snan) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_negative(float nofpclass(ninf nzero nsub nnorm) %arg) {
; CHECK-LABEL: define nofpclass(inf nzero nsub nnorm) float @ret_atan_no_negative(
; CHECK-SAME: float nofpclass(ninf nzero nsub nnorm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nzero nsub nnorm) float @llvm.atan.f32(float nofpclass(ninf nzero nsub nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

; Input classes: fcNegative.

define float @ret_atan_no_positive_mode_ieee_ieee(
; CHECK-LABEL: define nofpclass(inf pzero psub pnorm) float @ret_atan_no_positive_mode_ieee_ieee(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf pzero psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: ieee|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_ieee_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_ieee_positivezero(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: ieee|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_ieee_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_ieee_dynamic(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR4:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: ieee|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_positivezero_ieee(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_positivezero_ieee(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR5:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_positivezero_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_positivezero_positivezero(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR6:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_positivezero_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_positivezero_dynamic(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR7:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_dynamic_ieee(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_dynamic_ieee(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR8:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_dynamic_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_dynamic_positivezero(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR9:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_mode_dynamic_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_mode_dynamic_dynamic(
; CHECK-SAME: float nofpclass(pinf pzero psub pnorm) [[ARG:%.*]]) #[[ATTR10:[0-9]+]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

; Input classes: fcNegative & ~fcNegSubnormal.

define float @ret_atan_no_positive_negsubnormal(
; CHECK-LABEL: define nofpclass(inf pzero psub pnorm) float @ret_atan_no_positive_negsubnormal(
; CHECK-SAME: float nofpclass(pinf pzero sub pnorm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf pzero psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero sub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero sub pnorm) %arg) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negsubnormal_mode_dynamic_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negsubnormal_mode_dynamic_dynamic(
; CHECK-SAME: float nofpclass(pinf pzero sub pnorm) [[ARG:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf pzero sub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf pzero sub pnorm) %arg)
  denormal_fpenv(float: dynamic|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}


; Input classes: fcNegative & ~fcNegZero.

define float @ret_atan_no_positive_negzero_mode_ieee_ieee(
; CHECK-LABEL: define nofpclass(inf pzero psub pnorm) float @ret_atan_no_positive_negzero_mode_ieee_ieee(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf pzero psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: ieee|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_ieee_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_ieee_positivezero(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: ieee|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_ieee_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_ieee_dynamic(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR4]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: ieee|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_positivezero_ieee(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_positivezero_ieee(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR5]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_positivezero_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_positivezero_positivezero(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR6]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_positivezero_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_positivezero_dynamic(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR7]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: positivezero|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_dynamic_ieee(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_dynamic_ieee(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR8]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_dynamic_positivezero(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_dynamic_positivezero(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_positive_negzero_mode_dynamic_dynamic(
; CHECK-LABEL: define nofpclass(inf psub pnorm) float @ret_atan_no_positive_negzero_mode_dynamic_dynamic(
; CHECK-SAME: float nofpclass(pinf zero psub pnorm) [[ARG:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf psub pnorm) float @llvm.atan.f32(float nofpclass(pinf zero psub pnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(pinf zero psub pnorm) %arg)
  denormal_fpenv(float: dynamic|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

; Input classes: fcPositive | fcNegSubnormal.

define float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_ieee(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_ieee(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: ieee|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_positivezero(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_positivezero(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: ieee|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_dynamic(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_ieee_dynamic(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR4]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: ieee|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_ieee(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_ieee(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR5]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: positivezero|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_positivezero(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_positivezero(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR6]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: positivezero|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_dynamic(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_positivezero_dynamic(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR7]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: positivezero|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_ieee(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_ieee(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR8]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: dynamic|ieee) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_positivezero(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_positivezero(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR9]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: dynamic|positivezero) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_dynamic(
; CHECK-LABEL: define nofpclass(inf) float @ret_atan_no_neginf_negnormal_negzero_mode_dynamic_dynamic(
; CHECK-SAME: float nofpclass(ninf nzero nnorm) [[ARG:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf) float @llvm.atan.f32(float nofpclass(ninf nzero nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nzero nnorm) %arg)
  denormal_fpenv(float: dynamic|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

; Input classes: fcPositive | fcNegZero.

define float @ret_atan_no_neginf_negnormal_negsubnormal(
; CHECK-LABEL: define nofpclass(inf nsub nnorm) float @ret_atan_no_neginf_negnormal_negsubnormal(
; CHECK-SAME: float nofpclass(ninf nsub nnorm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nsub nnorm) float @llvm.atan.f32(float nofpclass(ninf nsub nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nsub nnorm) %arg) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}

define float @ret_atan_no_neginf_negnormal_negsubnormal_mode_dynamic_dynamic(
; CHECK-LABEL: define nofpclass(inf nsub nnorm) float @ret_atan_no_neginf_negnormal_negsubnormal_mode_dynamic_dynamic(
; CHECK-SAME: float nofpclass(ninf nsub nnorm) [[ARG:%.*]]) #[[ATTR10]] {
; CHECK-NEXT:    [[CALL:%.*]] = call nofpclass(inf nsub nnorm) float @llvm.atan.f32(float nofpclass(ninf nsub nnorm) [[ARG]]) #[[ATTR11]]
; CHECK-NEXT:    ret float [[CALL]]
;
  float nofpclass(ninf nsub nnorm) %arg)
  denormal_fpenv(float: dynamic|dynamic) {
  %call = call float @llvm.atan.f32(float %arg)
  ret float %call
}
