; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -aa-pipeline=basic-aa -passes=attributor -attributor-manifest-internal -S < %s | FileCheck %s

declare float @llvm.sqrt.f32(float)

; sqrt cannot produce a subnormal result, so only the input denormal mode
; affects the following tests.

define float @ret_sqrt_ieee_psub(float nofpclass(nan inf zero nsub norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(nan inf zero sub nnorm) float @ret_sqrt_ieee_psub(
; CHECK-SAME: float nofpclass(nan inf zero nsub norm) [[ARG:%.*]]) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf zero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub norm) [[ARG]]) #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_ieee_nsub(float nofpclass(nan inf zero psub norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(snan inf zero sub nnorm) float @ret_sqrt_ieee_nsub(
; CHECK-SAME: float nofpclass(nan inf zero psub norm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf zero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero psub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_ieee_sub(float nofpclass(nan inf zero norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(snan inf zero sub nnorm) float @ret_sqrt_ieee_sub(
; CHECK-SAME: float nofpclass(nan inf zero norm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf zero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_ieee_pzero(float nofpclass(nan inf nzero sub norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(nan inf nzero sub nnorm) float @ret_sqrt_ieee_pzero(
; CHECK-SAME: float nofpclass(nan inf nzero sub norm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf nzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf nzero sub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_ieee_nzero(float nofpclass(nan inf pzero sub norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(nan inf pzero sub nnorm) float @ret_sqrt_ieee_nzero(
; CHECK-SAME: float nofpclass(nan inf pzero sub norm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf pzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf pzero sub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_ieee_zero(float nofpclass(nan inf sub norm) %arg) #0 {
; CHECK-LABEL: define nofpclass(nan inf sub nnorm) float @ret_sqrt_ieee_zero(
; CHECK-SAME: float nofpclass(nan inf sub norm) [[ARG:%.*]]) #[[ATTR1]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf sub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_daz_psub(float nofpclass(nan inf zero nsub norm) %arg) #1 {
; CHECK-LABEL: define nofpclass(nan inf nzero sub nnorm) float @ret_sqrt_daz_psub(
; CHECK-SAME: float nofpclass(nan inf zero nsub norm) [[ARG:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf nzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_daz_nsub(float nofpclass(nan inf zero psub norm) %arg) #1 {
; CHECK-LABEL: define nofpclass(snan inf pzero sub nnorm) float @ret_sqrt_daz_nsub(
; CHECK-SAME: float nofpclass(nan inf zero psub norm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf pzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero psub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_daz_sub(float nofpclass(nan inf zero norm) %arg) #1 {
; CHECK-LABEL: define nofpclass(snan inf sub nnorm) float @ret_sqrt_daz_sub(
; CHECK-SAME: float nofpclass(nan inf zero norm) [[ARG:%.*]]) #[[ATTR2]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_dapz_sub(float nofpclass(nan inf zero norm) %arg) #2 {
; CHECK-LABEL: define nofpclass(snan inf nzero sub nnorm) float @ret_sqrt_dapz_sub(
; CHECK-SAME: float nofpclass(nan inf zero norm) [[ARG:%.*]]) #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf nzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_dynamic_psub(float nofpclass(nan inf zero nsub norm) %arg) #3 {
; CHECK-LABEL: define nofpclass(nan inf nzero sub nnorm) float @ret_sqrt_dynamic_psub(
; CHECK-SAME: float nofpclass(nan inf zero nsub norm) [[ARG:%.*]]) #[[ATTR4:[0-9]+]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(nan inf nzero sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero nsub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_dynamic_nsub(float nofpclass(nan inf zero psub norm) %arg) #3 {
; CHECK-LABEL: define nofpclass(snan inf sub nnorm) float @ret_sqrt_dynamic_nsub(
; CHECK-SAME: float nofpclass(nan inf zero psub norm) [[ARG:%.*]]) #[[ATTR4]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero psub norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

define float @ret_sqrt_dynamic_sub(float nofpclass(nan inf zero norm) %arg) #3 {
; CHECK-LABEL: define nofpclass(snan inf sub nnorm) float @ret_sqrt_dynamic_sub(
; CHECK-SAME: float nofpclass(nan inf zero norm) [[ARG:%.*]]) #[[ATTR4]] {
; CHECK-NEXT:    [[SQRT:%.*]] = call nofpclass(snan inf sub nnorm) float @llvm.sqrt.f32(float nofpclass(nan inf zero norm) [[ARG]]) #[[ATTR5]]
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sqrt = call float @llvm.sqrt.f32(float %arg)
  ret float %sqrt
}

attributes #0 = { denormal_fpenv(ieee|ieee) }
attributes #1 = { denormal_fpenv(ieee|preservesign) }
attributes #2 = { denormal_fpenv(ieee|positivezero) }
attributes #3 = { denormal_fpenv(ieee|dynamic) }
